### ISSUE TITLE
IP Address is either not a valid IPv4/IPv6 address or falls within the private or reserved ranges

### ISSUE THREAD

**Issue by mirr** [codenexus/lumen-geoip#2]
I am developing locally using vagrant and I am getting this when passing my local IP. Is there a way to resolve this?

Thanks!

**Comment by cringer** [comment]
The application checks the detected IP to make sure it is valid and not within the private or reserved ip ranges.  It will never work correctly in terms of a lookup for a local IP.  You scan set a real IP by specifying it manually.

`app()->geoip->getLocation('128.101.101.101');`

I set some default data when using in development.

**Comment by cringer** [comment]
Resolved in #5c98f03
