### ISSUE TITLE
Service Provider not found

### ISSUE THREAD

**Issue by dawiyo** [codenexus/lumen-geoip#9]
Receiving this error when adding the service provider to bootstrap/app.php

```
[Symfony\Component\Debug\Exception\FatalThrowableError]  
Class 'Codenexus\GeoIP\GeoIPServiceProvider' not found   
```

**Comment by closca** [comment]
Hi, only way to have GeoIP working was to move the code inside app and create my on namespace.

**Comment by cringer** [comment]
Add autoload block to composer.json #10
